<?php
	$osmogu="<h2>O smogu</h2>
		<p>Wielu z nas często używa określenia smog kilka razy dziennie. Jednak nie każdy z nas wie dokładnie czym on jest. &bdquo;<em>Smog to ten dym co z komina sąsiada wychodzi</em>&rdquo;, powiedziałby niejeden z nas. I tak jest w tym nieco prawdy, ale po kolei.</br></br>
		Samo słowo smog pochodzi z angielskiego i jest połączeniem dw&oacute;ch sł&oacute;w: <em>smoke</em> (czyli dym) i <em>fog</em> (mgła). Powstaje on więc w wyniku mieszanki dymu, zanieczyszczeń i mgły. W Polsce mianem smogu określa się najczęściej zanieczyszczenia powstałe w wyniku proces&oacute;w spalania (w fabrykach, spaliny samochodowe, piece węglowe w domach). Na smog wlicza się kilka parametr&oacute;w &ndash; między innymi NO<sub>2</sub> (dwutlenek azotu) &ndash; powstały bezpośrednio w wyniku spalania, CO (tlenek węgla), CO<sub>2</sub> (dwutlenek węgla), jednak najpopularniejsze i najczęściej spotykane są dwa parametry: PM<sub>10</sub> oraz PM<sub>2.5</sub>. Czym są te tajemnicze nazwy? PM jest skr&oacute;tem z języka angielskiego - Particulate Matter, kt&oacute;ry oznacza cząstki stałe. Kolejną częścią nazwy jest numer: 10 i 2,5. Każdy z nich oznacza średnicę drobnych cząstek kt&oacute;re są zliczane w mikrometrach. Całą jednostką jest mikrogram na metr sześcienny, czyli na przykład wynik pomiaru parametru PM<sub>10</sub> &ndash; &nbsp;oznacza że w obszarze o długości, szerokości i wysokości r&oacute;wnej 1 metr, występuje 60 mikrogram&oacute;w cząstek o wielkości do 10 mikrometr&oacute;w. Wyjaśnia się tu także inne pytanie, kt&oacute;re może się nasunąć analizując wyniki: dlaczego PM<sub>10</sub> jest zawsze większe od PM<sub>2.5</sub>? Dzieje się tak, ponieważ w wynik tego pierwszego wlicza się także drugi, ponieważ cząstki mniejsze od &nbsp;spełniają warunek bycia mniejszym od 10 mikrometr&oacute;w.</br>
		Istotnym faktem są także polskie normy ustalające dopuszczalny poziom tych parametr&oacute;w. Bezpośrednio m&oacute;wi o nich Rozporządzenie Ministra Środowiska <a href='http://prawo.sejm.gov.pl/isap.nsf/download.xsp/WDU20120001031/O/D20121031.pdf' target='_blank'>(poz. 1031)</a> oraz <a href='http://prawo.sejm.gov.pl/isap.nsf/download.xsp/WDU20190001931/O/D20191931.pdf' target='_blank'>(poz.1931)</a>.</br>
		Skupiając się tylko na dw&oacute;ch ostatnich parametrach rozporządzenie m&oacute;wi wprost, że ustala się dla parametru PM<sub>10</sub> normę 24godzinną na poziomie oraz roczną na poziomie</br>
		Dla parametru PM<sub>2.5 </sub>ustalono jedynie normę roczną na poziomie &nbsp;(od stycznia 2020r.)</br>
		Opr&oacute;cz tego ustalono dla parametru PM<sub>10</sub> poziom alarmowy na poziomie &nbsp;(od października 2019) oraz poziom informowania na poziomie &nbsp;(od października 2019).</br>
		Zgodnie z Obwieszczeniem Marszałka Sejmu <a href='http://prawo.sejm.gov.pl/isap.nsf/download.xsp/WDU20190001396/T/D20191396L.pdf' target='_blank'> (poz. 1396)</a> poziom informowania oznacza stężenie substancji w powietrzu powyżej kt&oacute;rego istnieje zagrożenie zdrowia ludzkiego wynikające z kr&oacute;tkotrwałego narażenia na działanie zanieczyszczeń wrażliwych grup ludności w przypadku kt&oacute;rego niezbędna jest natychmiastowa informacja (na przykład, dzieci, starsi, kobiety w ciąży).</br>
		&nbsp;Poziom alarmowy natomiast oznacza natychmiastowe działanie służb w celu zmniejszenia zanieczyszczenia powietrza.</br>"
?>